# https://github.com/golangci/golangci-lint/blob/main/.golangci.yml

version: "2"

run:
  timeout: 2m

linters-settings:
  revive:
    exclude:
      - test-package
      - package-comments
      - unnecessary-init
      - var-declaration
      - builtin-shadow
      - varnamelen
    rules:
      - name: varnamelen
        arguments: [1]

linters:
  default: all
  enable:
    - govet
    - errcheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - mnd
    - goprintffuncname
    - gosec
    - intrange
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - tagliatelle
    - gochecknoglobals
    - mnd
    - testpackage
    - varnamelen
    - revive
    - paralleltest
    - gochecknoinits
    - funlen