# https://taskfile.dev

version: '3'

tasks:
  test:
    cmds:
      - golangci-lint fmt
      - go test -race -p=1 ./...
      - go test -race -v -bench=. -benchmem ./...
      - golangci-lint run ./...
