name: Build and Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        check-latest: true
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev
        sudo apt-get install -y libasound2-dev libpulse-dev
    
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        golangci-lint --version
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -race -p=1 ./... -v
    
    - name: Lint
      run: |
        golangci-lint fmt
        golangci-lint run ./...

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'
        check-latest: true
    
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        golangci-lint --version
      shell: bash
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -race -p=1 ./... -v
    
    - name: Lint
      run: |
        golangci-lint fmt
        golangci-lint run ./...
      shell: bash